export enum PRODUCT_ACTION_TYPES {
  SET_CURRENT_PRODUCT_START = 'product/SET_CURRENT_PRODUCT_START',
  SET_CURRENT_PRODUCT_SUCCESS = 'product/SET_CURRENT_PRODUCT_SUCCESS',
  SET_CURRENT_PRODUCT_FAILED = 'product/SET_CURRENT_PRODUCT_FAILED'
}
